// flow-typed signature: c38a8e1ab6a54679f2c7e6fa4cb1f36b
// flow-typed version: <<STUB>>/object-hash_v2.0.1/flow_v0.105.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-hash' {
	declare type Options = {
		algorithm?: 'sha1' | 'md5',
		excludeValues?: boolean,
		encoding?: 'buffer' | 'hex' | 'binary' | 'base64',
		ignoreUnknown?: boolean,
		replacer?: () => mixed,
		respectFunctionProperties?: boolean,
		respectFunctionNames?: boolean,
		respectType?: boolean,
		unorderedArrays?: boolean,
		unorderedSets?: boolean,
		unorderedObjects?: boolean,
		excludeKeys?: string => boolean,
	};

	declare function hash(value: any, options?: Options): string;

	declare function sha1(value: any): string;

	declare function keys(value: any): string;

	declare function MD5(value: any): string;

	declare function keysMD5(value: any): string;

	declare function writeToStream(
		value: any,
		options: Options,
		stream: WriteableStream,
	): void;

	declare module.exports: typeof hash & {
		sha1: typeof sha1,
		keys: typeof keys,
		MD5: typeof MD5,
		keysMD5: typeof keysMD5,
		writeToStream: typeof writeToStream,
	};
}
