// flow-typed signature: 5c5b89c103714aa21afa3b6a78e96f31
// flow-typed version: <<STUB>>/react-document-title_v2.0.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-document-title'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-document-title' {
	declare module.exports: React$ComponentType<{
		title: string,
		children?: React$Node,
	}>;
}
