// flow-typed signature: 53e732661f88d54d53161d8c62bbc7e6
// flow-typed version: <<STUB>>/redux-thunk-subscribe_v1.0.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk-subscribe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk-subscribe' {
	import type { StoreCreator } from 'redux';

	declare module.exports: {
		<S, A, D>(next: StoreCreator<S, A, D>): StoreCreator<S, A, D>,
		withExtraArgument<S, A, D>(
			any,
		): (next: StoreCreator<S, A, D>) => StoreCreator<S, A, D>,
	};
}
