module.exports = {
	plugins: ['import', 'no-use-extend-native', 'promise', 'unicorn', 'babel'],
	rules: {
		/*
		 * Errors
		 */
		'for-direction': 'error',
		'getter-return': 'error',
		'no-async-promise-executor': 'error',
		'no-await-in-loop': 'warn',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': 'error',
		'no-console': 'warn',
		'no-constant-condition': 'warn',
		'no-control-regex': 'error',
		'no-debugger': 'warn',
		'no-dupe-args': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-empty': 'warn',
		'no-empty-character-class': 'warn',
		'no-ex-assign': 'error',
		'no-extra-boolean-cast': 'warn',
		'no-func-assign': 'error',
		'no-inner-declarations': 'error',
		'no-invalid-regexp': 'error',
		'no-irregular-whitespace': 'error',
		'no-misleading-character-class': 'error',
		'no-obj-calls': 'error',
		'no-prototype-builtins': 'error',
		'no-regex-spaces': 'warn',
		'no-sparse-arrays': 'error',
		'no-template-curly-in-string': 'warn',
		'no-unreachable': 'warn',
		'no-unsafe-finally': 'error',
		'no-unsafe-negation': 'warn',
		'require-atomic-updates': 'warn',
		'use-isnan': 'error',
		'valid-typeof': 'error',

		'no-dupe-class-members': 'error',
		'no-delete-var': 'error',
		'no-shadow-restricted-names': 'error',
		'constructor-super': 'warn',
		'no-class-assign': 'warn',
		'no-const-assign': 'error',
		'no-new-symbol': 'error',
		'no-this-before-super': 'error',
		'require-yield': 'warn',
		'no-case-declarations': 'error',
		'no-catch-shadow': 'warn',
		'no-empty-pattern': 'warn',
		'no-global-assign': 'error',
		'babel/no-invalid-this': 'error',
		'no-new-require': 'error',
		'no-octal': 'error',
		'import/no-unresolved': 'error',
		'import/named': 'error',
		'import/default': 'error',
		'import/namespace': 'error',
		'import/no-absolute-path': 'warn',
		'import/no-dynamic-require': 'warn',
		'import/no-webpack-loader-syntax': 'warn',
		'import/no-self-import': 'warn',
		'import/no-useless-path-segments': 'warn',
		'import/export': 'error',
		'import/no-named-as-default': 'warn',
		'import/no-named-as-default-member': 'error',
		'import/no-deprecated': 'warn',
		'import/no-extraneous-dependencies': [
			'warn',
			{
				devDependencies: false,
				optionalDependencies: false,
			},
		],
		'import/no-mutable-exports': 'warn',
		'import/no-duplicates': 'error',
		'import/unambiguous': 'error',
		'promise/valid-params': 'error',
		'unicorn/explicit-length-check': [
			'error',
			{
				'non-zero': 'greater-than',
			},
		],
		'unicorn/no-unsafe-regex': 'error',

		/*
		 * Best practices
		 */
		'accessor-pairs': 'warn',
		'array-callback-return': 'warn',
		'block-scoped-var': 'warn',
		'class-methods-use-this': 'warn',
		'consistent-return': 'warn',
		'default-case': 'warn',
		'dot-notation': 'warn',
		eqeqeq: [
			'warn',
			'always',
			{
				null: 'ignore',
			},
		],
		'guard-for-in': 'warn',
		'no-alert': 'warn',
		'no-caller': 'warn',
		'no-div-regex': 'warn',
		'no-else-return': 'warn',
		'no-empty-function': 'warn',
		'no-eval': 'warn',
		'no-extend-native': 'warn',
		'no-use-extend-native/no-use-extend-native': 'warn',
		'no-extra-bind': 'warn',
		'no-extra-label': 'warn',
		'no-implicit-coercion': 'warn',
		'no-implicit-globals': 'warn',
		'no-implied-eval': 'warn',
		'no-iterator': 'warn',
		'no-labels': 'warn',
		'no-lone-blocks': 'warn',
		'no-loop-func': 'warn',
		'no-multi-str': 'warn',
		'no-new': 'warn',
		'no-new-func': 'warn',
		'no-new-wrappers': 'warn',
		'unicorn/new-for-builtins': 'warn',
		'no-octal-escape': 'warn',
		'no-param-reassign': [
			'warn',
			{
				props: true,
			},
		],
		'no-proto': 'warn',
		'no-redeclare': [
			'warn',
			{
				builtinGlobals: true,
			},
		],
		'no-return-assign': ['warn', 'always'],
		'no-return-await': 'warn',
		'no-script-url': 'warn',
		'no-self-assign': [
			'warn',
			{
				props: true,
			},
		],
		'no-self-compare': 'warn',
		'no-sequences': 'warn',
		'no-throw-literal': 'warn',
		'no-unmodified-loop-condition': 'warn',
		'no-unused-expressions': 'off',
		'babel/no-unused-expressions': 'warn',
		'no-unused-labels': 'warn',
		'no-useless-call': 'warn',
		'no-useless-concat': 'warn',
		'no-useless-escape': 'warn',
		'no-useless-return': 'warn',
		'no-void': 'warn',
		'no-with': 'warn',
		'prefer-object-spread': 'warn',
		'prefer-promise-reject-errors': 'warn',
		radix: ['warn', 'always'],
		'require-await': 'warn',
		'require-unicode-regexp': 'warn',
		'vars-on-top': 'warn',
		yoda: [
			'warn',
			'never',
			{
				exceptRange: true,
			},
		],
		'no-label-var': 'warn',
		'no-undef': [
			'warn',
			{
				typeof: true,
			},
		],
		'no-unused-vars': [
			'warn',
			{
				args: 'all',
				argsIgnorePattern: '^_$',
				caughtErrors: 'all',
				varsIgnorePattern: '^_$',
			},
		],
		'no-use-before-define': 'warn',
		'callback-return': 'warn',
		'global-require': 'warn',
		'handle-callback-err': 'warn',
		'no-useless-computed-key': 'warn',
		'no-useless-constructor': 'warn',
		'no-useless-rename': 'warn',
		'no-var': 'warn',
		'prefer-const': 'warn',
		'symbol-description': 'warn',
		'no-fallthrough': 'warn',
		'no-path-concat': 'warn',
		'no-process-exit': 'warn',
		'no-sync': 'warn',
		'unicorn/catch-error-name': 'warn',
		'unicorn/no-process-exit': 'warn',
		'unicorn/error-message': 'warn',
		'unicorn/prefer-add-event-listener': 'warn',
		// NB: This is safe to turn off if there’s static type checking
		'unicorn/no-fn-reference-in-iterator': 'warn',
		'promise/catch-or-return': 'warn',
		'promise/no-return-wrap': 'warn',
		'promise/param-names': 'warn',
		'promise/always-return': 'warn',
		'promise/no-nesting': 'warn',
		'promise/no-promise-in-callback': 'warn',
		'promise/no-callback-in-promise': 'warn',
		'promise/avoid-new': 'warn',
		'promise/no-new-statics': 'warn',
		'promise/no-return-in-finally': 'warn',
		'promise/prefer-await-to-then': 'warn',

		/*
		 * Style
		 */
		'init-declarations': 'warn',
		'no-undef-init': 'warn',
		camelcase: 'warn',
		'consistent-this': ['warn', 'unsafeThat'],
		'func-name-matching': 'warn',
		'func-names': ['warn', 'as-needed'],
		'func-style': 'warn',
		'lines-between-class-members': 'warn',
		'babel/new-cap': 'warn',
		'no-array-constructor': 'warn',
		'no-bitwise': 'warn',
		'no-continue': 'warn',
		'no-lonely-if': 'warn',
		'no-multi-assign': 'warn',
		'no-new-object': 'warn',
		'no-plusplus': 'warn',
		'no-underscore-dangle': 'warn',
		'no-unneeded-ternary': 'warn',
		'one-var': ['warn', 'never'],
		'operator-assignment': 'warn',
		'semi-spacing': 'warn',
		'semi-style': 'warn',
		'spaced-comment': [
			'warn',
			'always',
			{
				markers: ['*'],
			},
		],
		'arrow-body-style': ['warn', 'as-needed'],
		'object-shorthand': 'warn',
		'prefer-arrow-callback': 'warn',
		'prefer-numeric-literals': 'warn',
		'prefer-rest-params': 'warn',
		'prefer-spread': 'warn',
		'unicorn/prefer-spread': 'warn',
		'prefer-template': 'warn',
		'sort-imports': 'off',
		'import/order': [
			'warn',
			{
				'newlines-between': 'always',
			},
		],
		'unicorn/throw-new-error': 'warn',
		'unicorn/number-literal-case': 'warn',
		'unicorn/escape-case': 'warn',
		'unicorn/no-array-instanceof': 'warn',
		'unicorn/no-hex-escape': 'warn',
		'unicorn/custom-error-definition': 'warn',
		'unicorn/prefer-starts-ends-with': 'warn',
		'unicorn/prefer-type-error': 'warn',
		'unicorn/regex-shorthand': 'warn',
		'unicorn/prefer-exponentiation-operator': 'warn',
		'import/first': 'warn',
		'import/extensions': ['warn', 'ignorePackages'],
		'import/newline-after-import': 'warn',
		'import/prefer-default-export': 'warn',
		'import/no-unassigned-import': 'warn',
		'import/no-named-default': 'warn',
	},
};
